# Generated by Django 4.2.1 on 2023-05-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSV_reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Family', models.TextField(blank=True, null=True)),
                ('Product_Code', models.TextField(blank=True, max_length=255, null=True)),
                ('Product_Description', models.TextField(blank=True, max_length=255, null=True)),
                ('Quantity_In_Stock', models.CharField(max_length=255)),
                ('Available_Quantity', models.FloatField(default=0)),
                ('Allocated_Quantity', models.FloatField(default=0)),
                ('Price', models.FloatField(default=0)),
                ('Divider', models.FloatField(default=0)),
            ],
        ),
    ]
