# Generated by Django 4.2.1 on 2023-05-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='vote_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
